name: deploy

on:
  push:
    branches: [main]

jobs:
  build:
    name: run dev container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./firstlab
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/firstlab:latest

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/firstlab:latest
            sudo docker stop lab1 || true
            sudo docker rm lab1 || true
            sudo docker run -d --name lab1 --restart unless-stopped -p 5173:5173 ${{ secrets.DOCKERHUB_USERNAME }}/firstlab:latest